# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {}
  required_version = "~> 1.1" # Only update this whenever Terraform version in Atlantis changes
}

provider "aws" {
  region  = var.region
  shared_credentials_file = "~/.aws/config"
}
